#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

# branches to build
branches:
  # whitelist
  only:
    - master
    
# Build worker image (VM template)
#image: Visual Studio 2015

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# scripts to run before build
before_build:
    - nuget restore
build:
  parallel: true                  # enable MSBuild parallel builds
  project: VShop.sln              # path to Visual Studio solution or project
  publish_wap: false              # package Web Application Projects (WAP) for Web Deploy
  publish_wap_xcopy: false        # package Web Application Projects (WAP) for XCopy deployment
  publish_azure: false            # package Azure Cloud Service projects and push to artifacts
  publish_nuget: true             # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: true     # generate and publish NuGet symbol packages
  include_nuget_references: true  # add -IncludeReferencedProjects option while packaging NuGet artifacts

# MSBuild verbosity level
#verbosity: quiet|minimal|normal|detailed
  verbosity: normal

#---------------------------------#
#       test configuration        #
#---------------------------------#
test:
  # only assemblies to test
  assemblies:
    only:
      - VShop.UnitTest.dll

  # only categories to test
  categories:
    only:
      - A
      - B
# scripts to run before tests
before_test:


# scripts to run after tests
after_test:

# to run your custom scripts instead of automatic tests
test_script:
  vstest.console /logger:Appveyor "C:\projects\VShop\VShop.UnitTest\bin\$(configuration)\VShop.UnitTest.dll" /Settings:Local.RunSettings /InIsolation /Framework:framework40
# upload results to AppVeyor
#$wc = New-Object 'System.Net.WebClient'
#$wc.UploadFile("https://ci.appveyor.com/api/testresults/mstest/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\xunit-results.xml))
# to disable automatic tests
#test: off
