#---------------------------------#
#      general configuration      #
#---------------------------------#
# version format
version: 1.0.{build}
os: Visual Studio 2015
# branches to build
environment:
  DELAY_TOLERANCE_MS: 50
  TIMING_GRANULARITY_MS: 30
init:
- git config --global core.autocrlf true
branches:
  # whitelist
  only:
    - master    
# Build worker image (VM template)
#image: Visual Studio 2015
#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU
# build Configuration, i.e. Debug, Release, etc.
configuration: Release
# scripts to run before build
before_build:
    - nuget restore
build:
  parallel: true                  # enable MSBuild parallel builds
  project: VShop.sln              # path to Visual Studio solution or project
  publish_wap: false              # package Web Application Projects (WAP) for Web Deploy
  publish_wap_xcopy: false        # package Web Application Projects (WAP) for XCopy deployment
  publish_azure: false            # package Azure Cloud Service projects and push to artifacts
  publish_nuget: true             # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: true     # generate and publish NuGet symbol packages
  include_nuget_references: true  # add -IncludeReferencedProjects option while packaging NuGet artifacts

# MSBuild verbosity level
#verbosity: quiet|minimal|normal|detailed
  verbosity: normal

build_script:

#---------------------------------#
#       test configuration        #
#---------------------------------#
test:
  assemblies:
    only:
      - '**\*.UnitTest.dll'
  categories:
    only:
      - A
      - B
before_test:

test_script:
  vstest.console /logger:Appveyor C:\projects\vshop\VShop.UnitTest\bin\%CONFIGURATION%\VShop.UnitTest.dll /InIsolation /Enablecodecoverage /UseVsixExtensions:true /Framework:framework45
# after_test:
#   - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"vstest.console.exe" -targetargs:"C:\projects\vshop\VShop.UnitTest\bin\%CONFIGURATION%\VShop.UnitTest.dll" -filter:"+[Rackspace*]* +[UnitTest*]*" -excludebyattribute:*.ExcludeFromCodeCoverage* -hideskipped:All -output:.\vshop_coverage.xml
#   - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
#   - pip install codecov
#   - codecov -f "vshop_coverage.xml"
#$wc = New-Object 'System.Net.WebClient'
#$wc.UploadFile("https://ci.appveyor.com/api/testresults/mstest/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\vshop_coverage.xml))
